# Generated by Django 4.2.1 on 2023-05-08 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_remove_recipes_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredients',
            options={'verbose_name': 'ingredient', 'verbose_name_plural': 'ingredients'},
        ),
        migrations.AlterModelOptions(
            name='instructions',
            options={'verbose_name': 'instruction', 'verbose_name_plural': 'instructions'},
        ),
    ]
