# Generated by Django 4.2.1 on 2023-05-08 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_alter_recipes_preparation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='servings',
            field=models.IntegerField(help_text='number of servings'),
        ),
    ]
